name: Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - - name: Setup Flutter
      - uses: subosito/flutter-action@v2
      - with:
      - channel: stable
      - flutter-version: 3.35.7


      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --dart-define=API_URL=https://crm-application-zaaturn.up.railway.app

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
